### ISSUE TITLE
Implement reasonable timeouts for requests

### ISSUE THREAD

**Issue by joshtemple** [dbanalyticsco/spectacles#19]
See documentation [here](https://2.python-requests.org/en/master/user/quickstart/#timeouts)

>Nearly all production code should use this parameter in nearly all requests. Failure to do so can cause your program to hang indefinitely

10 minutes seems reasonable to me to start with, recognizing that there are probably some queries and slow databases.

**Comment by DylanBaker** [comment]
That makes sense. Can it be set against the session? 

We might also want to make it configurable in case a user is aware of particularly long running queries on their side and wants to extend it?
