### ISSUE TITLE
Model/explore selection

### ISSUE THREAD

**Issue by DylanBaker** [dbanalyticsco/spectacles#21]
When running Fonz, you should be able to select which models and/or explores you want to query (and possibly exclude which models/explore as well?)

I have found this to be a necessary feature when testing work locally from my terminal as you don't want to waste time fetching dimensions and running queries for explores or models you aren't interested in testing at that point in time. 

I've thought of a few ways to possible tackle this:

- Separate `--model` and `--explore` options: For models, I think this is reasonably straightforward. You would pass the model(s) in question to the `--model` option. For explores, I think it's a bit more complicated. You could have it done exclusively through the `--explore` flag, where you specific the explore with the model prefixed, i.e. `--explore ecommerce.orders`. Alternatively, you could set it up so that it uses the model and explore flags in aggregate. You would define the model via the model flag and then the explores within it with the explore flag. This gets more complicated if you want to query from multiple models (where they even possibly have explores of the same name).

- A single flag (let's call it `--explores` for now) with dbt-like parsing. i.e. `ecommerce` and/or `ecommerce.*` would run all explores in the ecommerce model and `ecommerce.orders` would run it on the orders explore in the ecommerce model. This seems like the better solution to me. We would simply have to parse the options passed and split on the `.`. This would also extend to an exclude syntax more easily.

**Comment by joshtemple** [comment]
I'm anticipating people may want to do the opposite as well: run everything but exclude a certain model or explore(s). This should be its own issue, but noting that we'll want to consider that preference soon.
